15:43:21  Running with dbt=1.10.13
15:43:21  dbt version: 1.10.13
15:43:21  python version: 3.13.8
15:43:21  python path: C:\Users\hbenabdallah\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
15:43:21  os info: Windows-11-10.0.26200-SP0
15:43:29  Using profiles dir at C:\Users\hbenabdallah\.dbt
15:43:29  Using profiles.yml file at C:\Users\hbenabdallah\.dbt\profiles.yml
15:43:29  Using dbt_project.yml file at dbt_sql_data_warehouse\dbt_project.yml
15:43:29  adapter type: snowflake
15:43:29  adapter version: 1.10.2
15:43:30  Configuration:
15:43:30    profiles.yml file [OK found and valid]
15:43:30    dbt_project.yml file [OK found and valid]
15:43:30  Required dependencies:
15:43:31   - git [OK found]

15:43:31  Connection:
15:43:31    account: EMGGQRU-HY48053
15:43:31    user: HELMIJEMS
15:43:31    database: POC2
15:43:31    warehouse: COMPUTE_WH
15:43:31    role: ACCOUNTADMIN
15:43:31    schema: PUBLIC
15:43:31    authenticator: None
15:43:31    oauth_client_id: None
15:43:31    query_tag: dbt_sql_data_warehouse
15:43:31    client_session_keep_alive: False
15:43:31    host: None
15:43:31    port: None
15:43:31    proxy_host: None
15:43:31    proxy_port: None
15:43:31    protocol: None
15:43:31    connect_retries: 1
15:43:31    connect_timeout: None
15:43:31    retry_on_database_errors: False
15:43:31    retry_all: False
15:43:31    insecure_mode: False
15:43:31    reuse_connections: True
15:43:31    s3_stage_vpce_dns_name: None
15:43:31  Registered adapter: snowflake=1.10.2
15:43:40    Connection test: [OK connection ok]

15:43:40  All checks passed!
